#! /bin/bash
rm --f *.tex
rm --f *.toc
rm --f *.aux
rm --f *.log
rm --f *.out
rm --f ./*_files/*.png
rm --f book.ipynb
rm --f book.toc
rm --f book.tex
rm --f short.ipynb
rm --f chapter.ipynb
rm --f chapter.pdf
rm -r ./tmp/*
rmdir tmp


rmdir  ./*_files/ 2> /dev/null

if (( $# == 1)); then
  if [ "@1" == all ]; then
    rm book.pdf;
  fi 
fi
